## 이상치 제거

- 타석(PA) lower bound 제거하기
- 장타율 or 타율 0인 선수 제거
- 타자 파일에서 제거한 선수 pcode 선수파일에서 제거

In [1]:
import pandas as pd

# 한글 폰트 깨짐 방지
from matplotlib import font_manager, rc
font_path = "C:/Windows/Fonts/NGULIM.TTF"
font = font_manager.FontProperties(fname=font_path).get_name()
rc('font', family=font)

#에러 무시
import warnings
warnings.filterwarnings('ignore')

import pandas as pd

import matplotlib.pyplot as plt
import matplotlib

from sklearn.tree import export_graphviz
import graphviz

from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import GridSearchCV

from sklearn.preprocessing import scale, minmax_scale, robust_scale

import xgboost

import seaborn as sns

plt.rcParams['font.family'] = 'NanumGothic'

In [9]:
hts = pd.read_csv('hts.csv')
hitter = pd.read_csv('hitter.csv')
player = pd.read_csv('player.csv')

In [14]:
hts.rename(columns = {'GYEAR' : '연도', 
                      'G_ID' : '경기코드', 
                      'PIT_ID':'타구코드', 
                      'PCODE' : '선수코드', 
                      'T_ID' : '타자 팀 코드', 
                      'INN' : '이닝', 
                      'HIT_VEL' : '타구속도', 
                      'HIT_ANG_VER' : '발사각도', 
                      'HIT_RESULT' : '타격결과', 
                      'PIT_VEL' : '투구구속', 
                      'STADIUM' : '해당구장'}, inplace = True)

In [16]:
hitter.rename(columns = {'GYEAR' : '연도', 
                      'PCODE' : '선수코드', 
                      'GAMENUM':'경기', 
                      'PA' : '타석', 
                      'AB' : '타수', 
                      'BA' : '타율', 
                      'HIT' : '안타', 
                      'HR' : '홈런', 
                      'TOTB' : '루타', 
                      'SLG' : '장타율', 
                      'SF' : '희생플라이', 
                      'BB' : '볼넷', 
                      'KK' : '삼진', 
                      'IB' : '고의사구',
                      'HP' : '사구',
                      'GD' : '병살타'}, inplace = True)

In [18]:
player.rename(columns = {'GYEAR' : '연도', 
                      'PCODE' : '선수코드', 
                      'NAME':'선수명', 
                      'T_ID' : '팀코드', 
                      'POSITION' : '포지션', 
                      'AGE_VA' : '나이', 
                      'MONEY' : '연봉'}, inplace = True)

In [19]:
# 출루율 계산
hitter['출루율'] = ((hitter['안타']+hitter['볼넷']+hitter['사구'])/(hitter['타수']+hitter['볼넷']+hitter['사구']+hitter['희생플라이'])).round(3)

In [20]:
# OPS 계산
hitter['OPS'] = hitter['장타율'] + hitter['출루율']

In [21]:
hitter

,연도,선수코드,경기,타석,타수,타율,안타,홈런,루타,장타율,희생플라이,볼넷,삼진,고의사구,사구,병살타,출루율,OPS
0,2018,60100,70,169,152,0.243,37,3,63,0.414,1,12,36,0,4,5,0.314,0.728
1,2018,60184,6,10,10,0.200,2,0,3,0.300,0,0,3,0,0,0,0.200,0.500
2,2018,60288,1,1,1,0.000,0,0,0,0.000,0,0,0,0,0,0,0.000,0.000
3,2018,60343,83,174,162,0.216,35,8,63,0.389,0,8,49,0,3,3,0.266,0.655
4,2018,60456,4,8,6,0.500,3,0,3,0.500,0,2,0,0,0,0,0.625,1.125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1093,2021,79290,4,8,8,0.125,1,0,1,0.125,0,0,2,0,0,0,0.125,0.250
1094,2021,79365,73,261,219,0.265,58,16,117,0.534,1,32,69,0,6,5,0.372,0.906
1095,2021,79402,70,278,237,0.211,50,1,61,0.257,0,30,26,0,3,7,0.307,0.564
1096,2021,79456,62,135,124,0.274,34,0,38,0.306,2,7,11,1,1,5,0.313,0.619
1097,2021,79608,55,246,212,0.325,69,5,102,0.481,5,26,32,1,0,5,0.391,0.872